# Generated by Django 5.2.3 on 2025-06-25 11:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_trees', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_id', models.PositiveIntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Nil'), (1, 'TODO'), (2, 'INPROGRESS'), (3, 'DOUBT'), (4, 'DONE')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='portal.cube')),
            ],
            options={
                'ordering': ['tree_id'],
                'unique_together': {('cube', 'tree_id')},
            },
        ),
    ]
